// ============================================================
// pdfGen.js — PDF Generation Module
// Uses jsPDF (UMD, loaded via CDN) to generate a beautiful
// A4 Weekly Meal Plan + Grocery List document.
// ============================================================

/**
 * Collects data from the DOM and generates a PDF.
 * @param {Array}  mealData    - Array of day objects: { day, date, breakfast, lunch, dinner }
 * @param {Array}  groceryItems - Array of grocery strings
 * @param {string} weekRange   - Human-readable week range label
 */
export function generatePDF(mealData, groceryItems, weekRange) {
  // jsPDF is loaded as a global via CDN UMD build
  const { jsPDF } = window.jspdf;

  // ---- Document Setup ----
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageW  = doc.internal.pageSize.getWidth();   // 210mm
  const pageH  = doc.internal.pageSize.getHeight();  // 297mm
  const margin = 14;
  const usableW = pageW - margin * 2;
  let y = 0; // current vertical position cursor

  // ---- Color Palette ----
  const colors = {
    accentR: 99,  accentG: 102, accentB: 241, // Indigo #6366F1
    darkR: 26,    darkG: 29,    darkB: 46,     // #1A1D2E
    grayR: 100,   grayG: 116,   grayB: 139,    // #64748B
    lightR: 241,  lightG: 243,  lightB: 255,   // #F1F3FF (accent-light)
    borderR: 226, borderG: 232, borderB: 240,  // #E2E8F0
    greenR: 16,   greenG: 185,  greenB: 129,   // #10B981
    yellowR: 251, yellowG: 191, yellowB: 36,   // #FBBF24
    purpleR: 139, purpleG: 92,  purpleB: 246,  // #8B5CF6
    breakfastR: 245, breakfastG: 158, breakfastB: 11,  // amber
    lunchR: 5,    lunchG: 150,  lunchB: 105,   // emerald
    dinnerR: 124, dinnerG: 58,  dinnerB: 237,  // violet
    whiteR: 255,  whiteG: 255,  whiteB: 255,
    surfaceR: 250, surfaceG: 252, surfaceB: 255,
  };

  // ---- Helper: set fill color ----
  const setFill  = (r, g, b) => doc.setFillColor(r, g, b);
  const setStroke= (r, g, b) => doc.setDrawColor(r, g, b);
  const setFont  = (size, style = "normal", color = [26, 29, 46]) => {
    doc.setFontSize(size);
    doc.setFont("helvetica", style);
    doc.setTextColor(...color);
  };

  // ---- Helper: draw rounded rect ----
  const roundRect = (x, xY, w, h, r, fillOnly = true) => {
    if (fillOnly) doc.roundedRect(x, xY, w, h, r, r, "F");
    else          doc.roundedRect(x, xY, w, h, r, r, "FD");
  };

  // ============================================================
  // PAGE 1 — HEADER
  // ============================================================

  // Full-width gradient header background (simulated with solid fill)
  setFill(colors.accentR, colors.accentG, colors.accentB);
  doc.rect(0, 0, pageW, 42, "F");

  // Decorative accent bar (right side lighter tone)
  setFill(colors.purpleR, colors.purpleG, colors.purpleB);
  doc.rect(pageW - 40, 0, 40, 42, "F");

  // Header: emoji + title
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text("🥗 Weekly Meal Planner", margin, 17);

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(220, 221, 255);
  doc.text(`Week of ${weekRange}`, margin, 25);
  doc.text("Generated by weeklyMealPlanner.app", margin, 31);
  doc.text(new Date().toLocaleDateString("en-US", {
    weekday: "long", year: "numeric", month: "long", day: "numeric"
  }), margin, 37);

  y = 52;

  // ============================================================
  // SECTION TITLE: Meal Plan
  // ============================================================
  setFont(13, "bold", [colors.accentR, colors.accentG, colors.accentB]);
  doc.text("📅  WEEKLY MEAL PLAN", margin, y);

  // underline
  setStroke(colors.accentR, colors.accentG, colors.accentB);
  doc.setLineWidth(0.5);
  doc.line(margin, y + 2, margin + 60, y + 2);

  y += 8;

  // ============================================================
  // MEAL PLAN TABLE
  // ============================================================
  const days = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
  const colW = usableW;
  const mealColW = (usableW - 32) / 3; // 3 meal columns after day name col
  const dayColW = 32;
  const rowH = 14;
  const headerRowH = 8;

  // Table header row
  setFill(colors.accentR, colors.accentG, colors.accentB);
  roundRect(margin, y, colW, headerRowH, 2);
  doc.setFontSize(7.5);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text("DAY",       margin + 3,              y + 5.5);
  doc.text("☀️ BREAKFAST", margin + dayColW + 2,    y + 5.5);
  doc.text("🌿 LUNCH",     margin + dayColW + mealColW + 2,  y + 5.5);
  doc.text("🌙 DINNER",    margin + dayColW + mealColW * 2 + 2, y + 5.5);

  y += headerRowH;

  // Table rows
  mealData.forEach((item, idx) => {
    const rowY = y;
    const isEven = idx % 2 === 0;
    const isToday = item.isToday;

    // Row background
    if (isToday) {
      setFill(colors.lightR, colors.lightG, colors.lightB);
    } else if (isEven) {
      setFill(colors.surfaceR, colors.surfaceG, colors.surfaceB);
    } else {
      setFill(255, 255, 255);
    }
    roundRect(margin, rowY, colW, rowH, 0);

    // Row border
    setStroke(colors.borderR, colors.borderG, colors.borderB);
    doc.setLineWidth(0.2);
    doc.rect(margin, rowY, colW, rowH, "S");

    // Today highlight left border
    if (isToday) {
      setFill(colors.accentR, colors.accentG, colors.accentB);
      doc.rect(margin, rowY, 2, rowH, "F");
    }

    // Day name
    const dayName = item.day;
    const isWeekend = dayName === "Saturday" || dayName === "Sunday";
    setFont(8, "bold", isWeekend
      ? [colors.purpleR, colors.purpleG, colors.purpleB]
      : [colors.darkR, colors.darkG, colors.darkB]
    );
    doc.text(dayName.slice(0, 3).toUpperCase(), margin + 4, rowY + 5.5);

    // Date sub-label
    if (item.date) {
      setFont(6, "normal", [colors.grayR, colors.grayG, colors.grayB]);
      doc.text(item.date, margin + 4, rowY + 10);
    }

    // Column separator lines
    setStroke(colors.borderR, colors.borderG, colors.borderB);
    doc.setLineWidth(0.2);
    doc.line(margin + dayColW, rowY, margin + dayColW, rowY + rowH);
    doc.line(margin + dayColW + mealColW, rowY, margin + dayColW + mealColW, rowY + rowH);
    doc.line(margin + dayColW + mealColW * 2, rowY, margin + dayColW + mealColW * 2, rowY + rowH);

    // Meal text renderer
    const renderMealCell = (text, xStart, labelColor) => {
      const cellText = text && text.trim() ? text.trim() : "—";
      const lines = doc.splitTextToSize(cellText, mealColW - 5);
      const displayLines = lines.slice(0, 2); // max 2 lines per cell

      setFont(7.5, "normal", [colors.darkR, colors.darkG, colors.darkB]);
      doc.text(displayLines.join(" "), xStart + 3, rowY + 5.5, {
        maxWidth: mealColW - 5,
      });
    };

    renderMealCell(item.breakfast, margin + dayColW, [colors.breakfastR, colors.breakfastG, colors.breakfastB]);
    renderMealCell(item.lunch,     margin + dayColW + mealColW, [colors.lunchR, colors.lunchG, colors.lunchB]);
    renderMealCell(item.dinner,    margin + dayColW + mealColW * 2, [colors.dinnerR, colors.dinnerG, colors.dinnerB]);

    y += rowH;
  });

  // ============================================================
  // GROCERY LIST — starts on same page or new page
  // ============================================================
  y += 12;

  // Check if we need a new page
  if (y + 60 > pageH - 20) {
    doc.addPage();
    _drawPageHeader(doc, pageW, pageH, colors, weekRange);
    y = 52;
  }

  // Grocery section title
  setFont(13, "bold", [colors.greenR, colors.greenG, colors.greenB]);
  doc.text("🛒  GROCERY LIST", margin, y);

  setStroke(colors.greenR, colors.greenG, colors.greenB);
  doc.setLineWidth(0.5);
  doc.line(margin, y + 2, margin + 52, y + 2);

  y += 10;

  // Grocery hint
  setFill(236, 253, 245); // green-50
  roundRect(margin, y, colW, 8, 2);
  setFont(7, "italic", [colors.lunchR, colors.lunchG, colors.lunchB]);
  doc.text(`${groceryItems.length} item${groceryItems.length !== 1 ? "s" : ""} — check off as you shop!`, margin + 4, y + 5.5);
  y += 12;

  // Grocery Items — Two columns
  if (groceryItems.length === 0) {
    setFont(9, "italic", [colors.grayR, colors.grayG, colors.grayB]);
    doc.text("No grocery items added.", margin + 4, y);
    y += 10;
  } else {
    const grocItemH = 7.5;
    const numCols = 2;
    const grocColW = (usableW - 8) / numCols;

    groceryItems.forEach((item, idx) => {
      const col   = idx % numCols;
      const rowIdx = Math.floor(idx / numCols);
      const xPos   = margin + col * (grocColW + 8);
      const yPos   = y + rowIdx * grocItemH;

      // Check if we need a new page
      if (yPos + grocItemH > pageH - 20) {
        if (col === 0) {
          doc.addPage();
          _drawPageHeader(doc, pageW, pageH, colors, weekRange);
          y = 52 - rowIdx * grocItemH; // recalibrate
        }
      }

      const finalY = y + rowIdx * grocItemH;

      // Checkbox (empty square)
      setStroke(colors.grayR, colors.grayG, colors.grayB);
      setFill(255, 255, 255);
      doc.setLineWidth(0.5);
      doc.roundedRect(xPos, finalY - 4, 4.5, 4.5, 0.8, 0.8, "FD");

      // Item text
      const itemLabel = item.trim() || "";
      const itemLines = doc.splitTextToSize(itemLabel, grocColW - 10);
      setFont(8, "normal", [colors.darkR, colors.darkG, colors.darkB]);
      doc.text(itemLines[0], xPos + 6.5, finalY);

      // Subtle separator
      if (idx < groceryItems.length - 1) {
        setStroke(colors.borderR, colors.borderG, colors.borderB);
        doc.setLineWidth(0.1);
      }
    });

    // Update y after grocery items
    const numRows = Math.ceil(groceryItems.length / numCols);
    y += numRows * grocItemH + 8;
  }

  // ============================================================
  // FOOTER (each page)
  // ============================================================
  const totalPages = doc.internal.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    setFill(colors.accentR, colors.accentG, colors.accentB);
    doc.rect(0, pageH - 10, pageW, 10, "F");
    setFont(7, "normal", [220, 221, 255]);
    doc.text(
      `Weekly Meal Planner | Page ${p} of ${totalPages}`,
      pageW / 2, pageH - 3.5, { align: "center" }
    );
  }

  // ============================================================
  // SAVE FILE
  // ============================================================
  const safeRange = weekRange.replace(/[^a-zA-Z0-9-]/g, "_");
  doc.save(`meal-plan-${safeRange}.pdf`);
}

// ============================================================
// Private helper: draw running page header on subsequent pages
// ============================================================
function _drawPageHeader(doc, pageW, pageH, colors, weekRange) {
  doc.setFillColor(colors.accentR, colors.accentG, colors.accentB);
  doc.rect(0, 0, pageW, 14, "F");
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text(`🥗 Weekly Meal Planner — ${weekRange} (continued)`, 14, 9);
}
